[pytest]
pythonpath = .
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning:app\.main
    ignore::DeprecationWarning:fastapi\.applications
    ignore:.*Can't sort tables for DROP; an unresolvable foreign key dependency exists.*:sqlalchemy.exc.SAWarning
    ignore:PyPDF2 is deprecated\. Please move to the pypdf library instead\.:DeprecationWarning
