import type { LanguageCode } from "../types";
import type { DocumentType } from "./documentTypes";

export const UPLOAD_COPY = {
  vi: {
    title: "Tải tài liệu lên",
    subtitle: "Chọn đúng loại tài liệu, tải file PDF/PPTX và chạy AI review theo bộ tiêu chuẩn chấm đang kích hoạt.",
    steps: ["Chọn loại tài liệu", "Tải file", "Chạy review"],
    chooseType: "Chọn loại tài liệu",
    chooseTypeHint: "AI sẽ áp dụng khung tiêu chí, hướng dẫn phản hồi và nguyên tắc theo loại tài liệu bạn chọn.",
    uploadFile: "Tải file",
    options: "Bộ tiêu chuẩn chấm",
    recommendedVersion: "Đang dùng phiên bản khuyến nghị",
    criteriaNote: "AI sẽ áp dụng bộ tiêu chuẩn theo loại tài liệu bạn chọn.",
    idleTitle: "Kéo và thả file vào đây",
    idleLink: "hoặc bấm để chọn file",
    idleHint: "Định dạng hỗ trợ: PDF, PPTX (tối đa 100MB)",
    dragTitle: "Thả file để tải lên",
    uploading: "Đang tải lên",
    uploaded: "Đã tải lên",
    replace: "Thay file",
    invalidType: "File không được hỗ trợ. Vui lòng chọn PDF hoặc PPTX.",
    tooLarge: "File vượt quá 100MB. Vui lòng chọn file nhỏ hơn.",
    uploadFailed: "Upload thất bại. Vui lòng thử lại.",
    projectRequired: "Vui lòng chọn project trước khi upload.",
    retry: "Thử lại",
    chooseOther: "Chọn file khác",
    startReview: "Bắt đầu review",
    reviewing: "AI đang review...",
    rerunWithoutCache: "Chấm lại không dùng cache",
    rerunWithoutCacheHint: "Bật khi cần chạy lại hoàn toàn để lấy kết quả mới.",
    disabledHelper: "Vui lòng chọn loại tài liệu và tải file để bắt đầu review.",
    success: "Review hoàn tất",
    language: "Ngôn ngữ",
    version: "Version",
    selectedType: "Loại tài liệu",
    processingSteps: {
      read: "Đang đọc tài liệu",
      extract: "Đang trích xuất nội dung",
      grade: "Đang chấm điểm",
      recommend: "Đang tạo khuyến nghị",
    },
    projectDescription: "Ngữ cảnh dự án (Quan trọng)",
    projectDescriptionHint: "Nhập mục tiêu, đối tượng đọc hoặc yêu cầu đặc biệt. AI sẽ dựa vào đây để đưa ra nhận xét phù hợp nhất với thực tế dự án của bạn.",
    projectSelect: "Chọn dự án",
    createProject: "Tạo dự án",
    createProjectNew: "Tạo dự án mới",
    selectExistingProject: "Chọn project có sẵn",
    noProjectAvailable: "Chưa có dự án khả dụng",
    createProjectBeforeUpload: "Vui lòng tạo dự án trước khi upload.",
    noProjectDescription: "Không có mô tả",
    setMissingTitle: "Chưa có bộ đánh giá khả dụng",
    setMissingShortTitle: "Chưa có bộ đánh giá",
    setMissingDescription: "Vui lòng vào \"Bộ cấu hình đánh giá AI\" và bấm \"Tạo bộ đầu tiên\".",
    activeSetLabel: "Bộ tiêu chuẩn chấm đang dùng",
    activeSetNotConfigured: "[Auto] Chưa thiết lập",
    activeSetAutoNote: "Hệ thống tự động áp dụng cấu hình active mới nhất.",
    selectedSetNoCriteria: "Bộ tiêu chuẩn chấm đã chọn chưa có danh sách tiêu chí",
    detailInfo: "Thông tin chi tiết",
    hideDetailInfo: "Ẩn thông tin chi tiết",
    levelLabel: "Mức độ đánh giá",
    setStatusLabel: "Trạng thái set",
    scoringHintAria: "Gợi ý chấm điểm",
    rubricLabel: "Khung tiêu chí chấm điểm",
    promptLabel: "Hướng dẫn phản hồi AI",
    policyLabel: "Nguyên tắc đánh giá",
    requiredRulesLabel: "Quy tắc bắt buộc",
    rulesHashLabel: "Mã quy tắc",
    duplicateTitle: "Xác nhận nội dung trùng",
    duplicateDescription: "Nội dung giống version trước. Bạn vẫn muốn tạo version mới không?",
    duplicateConfirm: "Tạo version mới",
    duplicateCancel: "Hủy",
    reviewingMessage: "AI đang đọc tài liệu của bạn...",
    startOver: "Làm lại từ đầu",
    overallScoreLabel: "Điểm tổng quát",
    viewDetailReport: "Xem báo cáo chi tiết",
    aiAnalysisDesc: "AI đã phân tích tài liệu và đưa ra các đề xuất cải thiện.",
  },
  ja: {
    title: "アップロード",
    subtitle: "資料タイプを選択し、PDF/PPTX をアップロードして AI レビューを実行します。",
    steps: ["資料タイプ選択", "ファイルアップロード", "レビュー実行"],
    chooseType: "資料タイプを選択",
    chooseTypeHint: "選択した資料タイプに応じて評価基準とプロンプトを適用します。",
    uploadFile: "ファイルアップロード",
    options: "採点設定",
    recommendedVersion: "推奨バージョンを使用中",
    criteriaNote: "AI は選択した資料タイプの評価基準を適用します。",
    idleTitle: "ファイルをドラッグ＆ドロップ",
    idleLink: "またはクリックして選択",
    idleHint: "対応形式: PDF, PPTX（最大100MB）",
    dragTitle: "ファイルをドロップしてアップロード",
    uploading: "アップロード中",
    uploaded: "アップロード済み",
    replace: "差し替え",
    invalidType: "対応していないファイルです。PDF または PPTX を選択してください。",
    tooLarge: "ファイルが100MBを超えています。小さいファイルを選択してください。",
    uploadFailed: "アップロードに失敗しました。もう一度お試しください。",
    projectRequired: "アップロード前にプロジェクトを選択してください。",
    retry: "再試行",
    chooseOther: "別ファイルを選択",
    startReview: "レビュー開始",
    reviewing: "AI レビュー中...",
    rerunWithoutCache: "キャッシュを使わず再評価",
    rerunWithoutCacheHint: "完全に再実行して最新結果を取得したい場合に有効にします。",
    disabledHelper: "資料タイプを選択し、ファイルをアップロードするとレビューを開始できます。",
    success: "レビューが完了しました",
    language: "言語",
    version: "Version",
    selectedType: "資料タイプ",
    processingSteps: {
      read: "資料を読み込み中",
      extract: "内容を抽出中",
      grade: "スコアリング中",
      recommend: "推奨事項を生成中",
    },
    projectDescription: "プロジェクトの背景・文脈（重要）",
    projectDescriptionHint: "プロジェクトの目的、読者、または特別な要件を入力してください。AI はこれに基づいて、プロジェクトの実態に即した最適なフィードバックを提供します。",
    projectSelect: "プロジェクト選択",
    createProject: "プロジェクト作成",
    createProjectNew: "プロジェクト作成",
    selectExistingProject: "既存プロジェクトを選択",
    noProjectAvailable: "利用可能なプロジェクトがありません",
    createProjectBeforeUpload: "アップロード前にプロジェクトを作成してください。",
    noProjectDescription: "説明なし",
    setMissingTitle: "評価セットが未設定です",
    setMissingShortTitle: "評価セットが未設定です",
    setMissingDescription: "「Bộ cấu hình đánh giá AI」で「最初のセットを作成」を実行してください。",
    activeSetLabel: "使用中の採点セット",
    activeSetNotConfigured: "[Auto] 未設定",
    activeSetAutoNote: "システムが最新の active 設定を自動選択します。",
    selectedSetNoCriteria: "選択した採点セットの基準がありません",
    detailInfo: "情報詳細",
    hideDetailInfo: "詳細を隠す",
    levelLabel: "評価レベル",
    setStatusLabel: "Status",
    scoringHintAria: "採点ヒント",
    rubricLabel: "評価基準",
    promptLabel: "AI応答ガイド",
    policyLabel: "評価ポリシー",
    requiredRulesLabel: "必須ルール",
    rulesHashLabel: "ルールハッシュ",
    duplicateTitle: "同一内容の確認",
    duplicateDescription: "前回のバージョンと同じ内容です。新しいバージョンを作成しますか？",
    duplicateConfirm: "新バージョンを作成",
    duplicateCancel: "キャンセル",
    reviewingMessage: "AI が資料を読み込んでいます...",
    startOver: "最初から",
    overallScoreLabel: "総合スコア",
    viewDetailReport: "詳細レポートを見る",
    aiAnalysisDesc: "AI がドキュメントを分析し、改善案を生成しました。",
  },
  en: {
    title: "Upload Document",
    subtitle: "Select document type, upload PDF/PPTX and run AI review with active criteria set.",
    steps: ["Choose Type", "Upload File", "Run Review"],
    chooseType: "Select Document Type",
    chooseTypeHint: "AI will apply criteria, response guide, and policy based on selected type.",
    uploadFile: "Upload File",
    options: "Evaluation Options",
    recommendedVersion: "Using recommended version",
    criteriaNote: "AI will apply criteria based on your selection.",
    idleTitle: "Drag and drop file here",
    idleLink: "or click to select file",
    idleHint: "Supported: PDF, PPTX (max 100MB)",
    dragTitle: "Drop to upload",
    uploading: "Uploading",
    uploaded: "Uploaded",
    replace: "Replace file",
    invalidType: "Unsupported file. Please select PDF or PPTX.",
    tooLarge: "File exceeds 100MB.",
    uploadFailed: "Upload failed. Please try again.",
    projectRequired: "Please select a project before uploading.",
    retry: "Retry",
    chooseOther: "Choose another file",
    startReview: "Start Review",
    reviewing: "AI is reviewing...",
    rerunWithoutCache: "Rerun without cache",
    rerunWithoutCacheHint: "Enable this to bypass cache and get fresh results.",
    disabledHelper: "Select type and upload file to start review.",
    success: "Review Completed",
    language: "Language",
    version: "Version",
    selectedType: "Document Type",
    processingSteps: {
      read: "Reading document",
      extract: "Extracting content",
      grade: "Scoring",
      recommend: "Generating recommendations",
    },
    projectDescription: "Project Context (Important)",
    projectDescriptionHint: "Enter goals, target audience, or special requirements. AI will use this to provide feedback tailored to your project's reality.",
    projectSelect: "Select Project",
    createProject: "Create Project",
    createProjectNew: "Create New Project",
    selectExistingProject: "Choose Existing Project",
    noProjectAvailable: "No projects available",
    createProjectBeforeUpload: "Please create a project first.",
    noProjectDescription: "No description provided",
    setMissingTitle: "No Evaluation Set Available",
    setMissingShortTitle: "No Evaluation Set",
    setMissingDescription: "Please go to \"AI Configuration\" and create your first set.",
    activeSetLabel: "Active Evaluation Set",
    activeSetNotConfigured: "[Auto] Not configured",
    activeSetAutoNote: "System automatically applies the latest active configuration.",
    selectedSetNoCriteria: "Selected set has no criteria defined",
    detailInfo: "Detailed Info",
    hideDetailInfo: "Hide Details",
    levelLabel: "Evaluation Level",
    setStatusLabel: "Status",
    scoringHintAria: "Scoring hint",
    rubricLabel: "Grading Rubric",
    promptLabel: "AI Response Guide",
    policyLabel: "Evaluation Policy",
    requiredRulesLabel: "Required Rules",
    rulesHashLabel: "Rules Hash",
    duplicateTitle: "Duplicate Content Detected",
    duplicateDescription: "Content is identical to the previous version. Create a new version anyway?",
    duplicateConfirm: "Create New Version",
    duplicateCancel: "Cancel",
    reviewingMessage: "AI is reading your document...",
    startOver: "Start Over",
    overallScoreLabel: "Overall Score",
    viewDetailReport: "View Detailed Report",
    aiAnalysisDesc: "AI has analyzed your document and generated actionable improvement suggestions.",
  },
} as const;

export const DOCUMENT_CARD_COPY: Record<
  LanguageCode,
  Record<DocumentType, { title: string; description: string; example: string; tooltip: string }>
> = {
  vi: {
    "project-review": {
      title: "Tài liệu nhìn nhận dự án",
      description: "Review tài liệu tổng kết, proposal, pitch deck hoặc báo cáo dự án.",
      example: "Ví dụ: page retrospective, báo cáo tiến độ, proposal khách hàng.",
      tooltip: "AI đánh giá tổng thể, điểm tốt, điểm cần cải thiện và chính sách cải thiện.",
    },
    "bug-analysis": {
      title: "Tài liệu phân tích bug",
      description: "Review bug report, phân tích nguyên nhân và đề xuất phòng ngừa.",
      example: "Ví dụ: issue report, RCA, defect analysis.",
      tooltip: "AI đánh giá khả năng tái hiện, phân tích nguyên nhân, ảnh hưởng và phòng ngừa.",
    },
    "qa-review": {
      title: "Tài liệu QA",
      description: "Review checklist, test case, test report hoặc tài liệu kiểm thử.",
      example: "Ví dụ: test plan, test result, QA checklist.",
      tooltip: "AI đánh giá độ phủ, độ rõ ràng, khả năng truy vết và tính thực thi.",
    },
    "explanation-review": {
      title: "Tài liệu giải thích",
      description: "Review tài liệu hướng dẫn, giải thích nghiệp vụ hoặc technical note.",
      example: "Ví dụ: user guide, design note, specification.",
      tooltip: "AI đánh giá tính dễ hiểu, logic, ví dụ minh họa và độ đầy đủ.",
    },
  },
  ja: {
    "project-review": {
      title: "プロジェクト振り返り資料",
      description: "総括、提案、ピッチデック、プロジェクトレポートをレビューします。",
      example: "例: retrospective page, 進捗レポート, 顧客提案。",
      tooltip: "総合評価、良い点、改善点、改善方針を評価します。",
    },
    "bug-analysis": {
      title: "バグ分析資料",
      description: "バグレポート、原因分析、再発防止策をレビューします。",
      example: "例: issue report, RCA, defect analysis。",
      tooltip: "再現性、原因分析、影響、予防策を評価します。",
    },
    "qa-review": {
      title: "QA 資料",
      description: "チェックリスト、テストケース、テストレポートをレビューします。",
      example: "例: test plan, test result, QA checklist。",
      tooltip: "カバレッジ、明確性、追跡性、実行可能性を評価します。",
    },
    "explanation-review": {
      title: "解説資料",
      description: "業務説明、手順書、technical note をレビューします。",
      example: "例: user guide, design note, specification。",
      tooltip: "分かりやすさ、論理性、例示、十分性を評価します。",
    },
  },
  en: {
    "project-review": {
      title: "Project Review Document",
      description: "Review project summaries, proposals, pitch decks, or reports.",
      example: "E.g., retrospective pages, progress reports, client proposals.",
      tooltip: "AI evaluates overall performance, strengths, improvements, and policies.",
    },
    "bug-analysis": {
      title: "Bug Analysis Document",
      description: "Review bug reports, root cause analysis, and prevention plans.",
      example: "E.g., issue reports, RCA, defect analysis.",
      tooltip: "AI evaluates reproducibility, root cause, impact, and prevention.",
    },
    "qa-review": {
      title: "QA Document",
      description: "Review checklists, test cases, test reports, or QA plans.",
      example: "E.g., test plans, test results, QA checklists.",
      tooltip: "AI evaluates coverage, clarity, traceability, and feasibility.",
    },
    "explanation-review": {
      title: "Explanation Document",
      description: "Review user guides, business explanations, or technical notes.",
      example: "E.g., user guides, design notes, specifications.",
      tooltip: "AI evaluates clarity, logic, examples, and completeness.",
    },
  },
};

